---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: observability
spec:
  encryptedData:
    admin-password: AgCYhCpzCrjpKpQTSjKoI5H7FrDm6VF7N+yNBTCNTBy0/tgeFzNp9gkUf2jZGvF5Y4Vfmot+MS/231amgU/t7T0QXzcKMHtSUPUVRynFq2O6UaSQxCr85KXoZlOd0hdE4eXX3mtwXeiHzCyjm4RwUzc+DU05YAhrTGXrHdweT8ZlJxnotS9u2wk0T/h/KVK/1/qz7WxjPvlaLrSAElqSExQGvVlespOktMLQUKymsop94/diRRVEAcVPPNPurf99DXwAwZoSsU8shQor+Cgy17WUQyfMcqoG/KHd2PoT/P2nx4brufe0gOoWjYhpSrgMVvTeb1i69x7hapiwTEPa6KVQg4sAPDQkukk5hdIXPuag/GS68v6rtVueDLznpQZ4xBaHLjyjpaTq2BmYZLTp5LyANWpQ8c3YCu8FC4j1TTedgtFo9AFEJMQmVS3GUnqsQttRiOwA4cxSmhAiQlWBW3Ojv3u2V49qPjTB7NJ2fIvtcHuMKuHooPdflJpMjj1bM2Jzts1aB7dLl1iBSbkG2dGxVjpq+V110pyCHNkjSQCfurGfVa/RFjh1yQsAj4sQpvePewbBxh8BfNtB7jtbJvpQgBHVyobI79Dzq1dp6DdBFaLQyy4s8UeTO/Df3fQODZYaZ907MdP+R0rZ5iJqWuya1XjfIai7g0et0aYSX9mfV7d2huM9Z1sr+DjD99pyIqDd9EjwOWPgyS1tbA==
    admin-user: AgCd9m7dioP8qxc7zRk/pYyltMetMnKwWHFsbYx5sGQ5mCaHLmqxgU8WZpYBBuTUpJWBLs25v0Jb4RA91mhYyHhruMwBBAOFW4biDFl3Xw/PuvGc9Sxraolr/qA3OCjwnjddwPzlBV9AFZYcWa2CEL8Tti8x2WDSF5hBSQdkmXGtF3SBxUsEJxNc3eoo2Ge56ps82wUPyZUbqg04nJm/kR0TX0L3sjSvjbSUaxwep9uby6V5EeZTTVOtlFmq6Knm7qvfnL89EPQeJebpJgvWmi5fOWkDbhBuXLBLSmhcpC/IIX0vidIz1ByNSciY8W1xtkKHR2LBEINMHpPaSs7oZTAQntHaXPga1r+NLm6EmENT7NW1tBPKxlY3wWAo/8LAs7hK0rpYuQE8+GkTUbJmNq20esR3m+rmBMR1yiKlg7CTgdTDQfnfxbw82ZwTnl3JkCFovXAc5UqxkmbAHjlMJ1QA9Y5RCVU5RxvpcMpjO/n+3erkwulxyUr39hogxepfUgVnqYZdfvp/Jlltq1yq65kBRgliQ/GMhNIp+b3Y86VhYaqEUuOzql40x+sZU1n9AbYPttzM2pC2FF5Wrfv9eUGOl8MbuEqDLozQnb34B7RAS3f/kjNCmsiOPM/OQYJotgYHkD/3s7etCV90ngWQGqP0oa/ov52bmc7zbdYrWCn4a2D7HPQhdlLhKptwQ3jCb/1ujIKgkg==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: observability
