apiVersion: clickhouse.com/v1alpha1
kind: ClickHouseCluster
metadata:
  name: clickhouse
  namespace: shared-data
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  shards: 1
  keeperClusterRef:
    name: clickhouse
  dataVolumeClaimSpec:
    accessModes:
      - ReadWriteOnce
    storageClassName: longhorn-bulk
    resources:
      requests:
        storage: 50Gi
  containerTemplate:
    image:
      repository: clickhouse/clickhouse-server
      tag: "26.4"
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        memory: 2Gi
  settings:
    defaultUserPassword:
      secret:
        name: clickhouse-auth
        key: password
