---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: clickhouse-auth
  namespace: shared-data
spec:
  encryptedData:
    password: AgCYb73PkfH9qujwcjY9vp/I5n2lV60zdWpPMFSlplJoMJIWVYqDKZ7linbuTLBdc1iwhowzhTw7yXR3m6PfXbo5r0rS/9AzTHSa+hB98xPCF5a+/ofnK0u1ZC3tOmbRx4R86cpFMF4SB3wRJVMtOXqB4obuIM4N03hoB79ZWEjMDI91u53PkCeJiYBt+FMTraFCJc4fEDfrSTJ6RuYf+A5GUJ11jiykp3Y3CmFvjwJ9jVDlQMy3VZCEFuseUhCvseM32Jwt+MjM4z/Fd9B9LT51v9Oyx9IJ9BvSvOVaM7sHNCHCtZUhrFFnbk0So7013L8+Njb/QdKWchwrBCzb+FsgvcuTY7xCv7B+OhDdWBJD04JuvflFzo/5iWOp+xx9EJaeE6P0TfkVJgfl7peUBmpyvxJoTl+CaYkjA91WCxqriU1jDZcgGht3EGHWbpAuEJqEoCQGuacjB+BdDONV/YdcxijtoQW8lzrMyI45Xm3eVUiyJUaCjsCiWkmil5/Xp31IcGoxE5krdfgfE9l45pydt4H4v8zfWZhvT1OKmEa5Z864Ex62s4tGd5vFB08hKEBUD2/TnERe09qCKwLHAqROCjVAnOUoSvUrntakPIMU4ygydXSruub1s047jh0Ri4NS5W5mbcqDc68VzGPUdTXg/YfMtUWd+aVVGcNcwRynSPBCc99N7MfN2YSr5mSq9YI919xjQbtv81XUxn8SuQHwlduxHF7im4YzjJSQyFKqOA==
  template:
    metadata:
      name: clickhouse-auth
      namespace: shared-data
