---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: security
spec:
  encryptedData:
    password: AgCfprjGo7LnrK7MeHwy5LVBiql7My9UxJhmZDB/MLQz1rpNt5+5A9G/LhtKbE4u+oXduDFV1mK91/YzmRH5Vrmt5snRBBGmzZ8yLTfXVCxu3PlkjZHjm1oaVj6mJmTsC9fa2E6FVD9iVWNDA5AoAETB+MJyeYb1AmiCOdamYaHShbOWOzrCe3w/m6sUjASM8w88nAgCGRa0WylUvSi/hzH+STA5HXNfZ2b5qYlglLirCpQH1OBlO2jgzQRZxzf9we7irS5JFoQYNV+s9gIzJiZCt10YMvl+GvuoTH+OArtJir0pWGwO/jwXDuYCKe3DTJ83vkeZeETd1Gva3J++3GN8JWRDMORv4HR9VJoZwymeCSFhPr+T73YzQCZWgKWs8qE31j00Q8nZmGf3KzyeAW9qAaDKt6HWB0cpLIjWiRDj0qeOcj0qavOXHrhZx6tf+3Qqxqm4eI5lsa95Agudd/0MI8CI8N9Jc8qmFazenX/A3Fn1NggB1Gjqd9T/8F265jpQh5yOhhT3qZvQHndlJbq9RiBdne74ckKDf36dYy1cnJKMJfMO0o4Ldnqn2YYhR+YkgJDblvfpa+lDBBoZj883Fy6asFPkeeXtiinTAEgSn/Qs6eAPjopk6zCWbVkCGfkEqvdw4nB8HgLkrXLeObeX68AeH7w+hY7pMaMgY1lnT6flw9CXTY7B4szfQg0y8AHMOMnlzZjRsve2QA==
    username: AgAIlPdKR/MmmYKcb0FswD/b4x+oFh1ysqdEtyl4bH9ocNRco48rdehiD5Vwc35H3Rlk9v+n3WEdxnYY9goe6qEbQwPc3WvthoARhfxXBz6G7PF3r2dEsp1kgeLn4ERzYdZxwQvI2VoSJshb9aHhhwmMLJ9S++V5GWkclVxlD8LsASY8ZggHXcAhSHRbebYZaiSOOhO1QgxCHPwk1QLVX0ZHh6/XzoRK60YbX0bebnpebDaEJ6aoHoFrAQUYOYhpYkhz5i7fNfqNF1W2abmMwVEFeDdQ/iRBuN2KkpBom9AOxRDcJSxCxDUGp0tORD6AgSOyjMMjw/ifT1WT2bAoCExzHonl2RonqH0N/Re/wuQFXVURIwZF71G31RdedqIMx57sLbcMIlrQSTxgR65zHSlxgGednFoR6AXyzmrxJ7pUDnD9ogkxdeiNT40SW02ueBqgs/rtUdsMpXJONQ1JcXB5ZHYM2WRNDi+0WImwBY+CKk2mAgSPWOHLxx3BDAQD5TlMaOM3/RHgRzIl3ZooFoVM46K8MogPAZqv5w+R0vog8d7LXCUafq7hqyjkih0u8yTalBMKARBaeFwHXxYiXPBmDbulJxhQ1SQZZsM1EBQkTZFA0PUWIwPdUmAFQTbljD0I4LsVgdikCiV3Ov1GhP0N2k+3FJr8lRlHsPQqEInqU6zAwldYkpDygvo66L5FirgksJCZBg==
  template:
    metadata:
      name: db-credentials
      namespace: security
