apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-setup
  namespace: security
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 5
  template:
    metadata:
      labels:
        app: keycloak-setup
    spec:
      restartPolicy: OnFailure
      containers:
        - name: keycloak-setup
          image: curlimages/curl:8.5.0
          command:
            - sh
            - /scripts/setup.sh
          env:
            - name: FRONTEND_URL
              value: "https://finance.naadroid.dev"
            - name: KEYCLOAK_ADMIN_USER
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin
                  key: password
          volumeMounts:
            - name: scripts
              mountPath: /scripts
              readOnly: true
      volumes:
        - name: scripts
          configMap:
            name: keycloak-setup-script
            defaultMode: 0755
