---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-superuser
  namespace: shared-data
spec:
  encryptedData:
    password: AgAR7G9GBGDfOC3imiXGdpDxkLSp3sGjofhtcFPG35K42vtvvtk0J4RCjc2b3AMM5/IsNchzO4awH8ew0XVtQH38YHPtre/ExLd58f09/SjEMc35aU80/4qVj7TlqMJBIBIrG/m4vTMVZ78TkT8qvUC9Qh1SyeIuwBVuzVQHY9P6hrxMtqxywXKQrQs+gjMtDeFiV0s9NZQet+lwjYvtV7HPaVcSXIfInkoo5iUwvtCExHVvExYRlSHVaWjFFJnkiSYYQP2X7v3opeGuoVlwe2Xyd2xFi2XEAxsqd0TckM0aFFjZusZrZo1ISphjTZT1fBbDuC4x4YgaHDmkmK23LIKkbuMPg6VhvGsHzNH4Bsz/gTzIIu4kK/FXVQICJ7RfwL+oMAWN1FZVEMelHQ0pl4hRtmPJqLM742VE/KqzLR4z73vtTgzmXqXKxs7jrGiHlwlKHYEW7bOdevbCpryPvqZpi7E/km2tY5X9INVYt1PtfNVpbeK1v7pVga1uuL/9dRnFHadq3rJm4DE52Vo9NwkKg/OUKRRttawjfovziSk8OPRE4x8z9sweB31DiFAy+S6sb1hhw5PSExyXaUX9TFsBHiVVygQtFmW1VMKUSSn39qDKJ9z4xB4K+UKiW9bDzE1InJJr7KWZaodf2wpyZoy5Wg84VOppuPMhyTgXkWixvhyiSrmgq+bkwsNfkdvi7azfPAZ2lQCHMIf/sg==
    postgresPassword: AgAhf2mxl48SNlRDIyf9FSt28Ytzwk3JewJtA3cPhV+nCjXryyc4CEvQfXFIo00HVTZRkbqKTSJjN9PAhHawbfTs8iJT4ombuEtttN5hVv0ODXS4KMZAqlnFfxdvNnim9rBX3KCnhra7P4f28zUkqjmzKekxgI7eBNTy0VibjXKpoly7g5myprMfve6SGfrhBmpGy2UAnwt9KQ6Q/fm8AtjaOsureQYcomt/DRKpWXOZKAnCniatleJJMZhY+YvnuPEkb1zNAM0r/MSGcFTgsDlHhlg9EQjAitHEOBOJWCp7IYwwC14slbHLbK4i34cSgKlEknqV+GyG1EF/eFCFgxeVN6IRRq08pkK8rNLbaW3TMCFLam9kxDMvnJcPa6nTjZQycWfhbUDqjn2rYL+xfoU3jJnDQS0iQD7QQqlMaozXiZogz7KSk9mfpP0POcsoLIMORoIShbRClPCVjo5sJundpaGRCs2VFBWcEC7D+AKDZFRSkmUDjtgZ65zn4oUjXh4y4+Qd8f8JZfVrIHbMdsf+0/nQL2JcgeRr7o1+yOsw7U3WbR9Ca2q0FOWsjriO3q6QjA67mfTURBV24WtNPTrq9p5k8+dSYW9vQLxQbqdGjjGCMoFlt28ZpYO34lLf2C9zJyRgDzMCxvqhnoT2SbIGFWNplCdV5AE6iwdmGAlzDXYUV3l4zzy+mPYIHujEdAKTrz4Toju/Uvm69g==
  template:
    metadata:
      name: postgres-superuser
      namespace: shared-data
