---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-superuser
  namespace: shared-data
spec:
  encryptedData:
    password: AgA1MqT0uIQ/CWsa3cBnQQiCfkEn4qOsyC6loubkXjbMoNC7Q8nLe5MrNzRKxhIrY7c4Smrgh8Kr9wFdwNB42J/JjmFj6B4aDvkK+2/04FQMLMvgfdnIqhjrbXizQ/wv+QgrHbwH/9xAzi4LhW2HiT6Rk12uokXnrwMt0eODHr+zgBtQ84hzk/v3wB5t1qEC6TiCYwG4bxdTpgXxfuUo74gLhVkNe/G8Ya2zD8BMy0u2Yvf8OhwxDXZAMRmsj+FQzkysfV5pVMbbkIY7oG5Io3R6HsUtSzyEe6aRPBrS9Fy5dWOO8xzEOrI4bKkzYc9bKhBT8Caz9xZbYwE4e9Bmx3KPOtwcf2Kc9lozhc5r8KVaMSmJYL2/1xW9fcdQear4kzHCDdXjgYpj7t+Fs3ohwPLwSSwYM6os1rGujoVSAqrTUK+CSafLjnA3Owfv5yFXmdk3wLOI210U8W4HRGs42PB8jiT+Fiw+kMUueOAVcljPbAEBE583Oeuw241ByCdAxR/pAvi34nhGAPufzSK13nJek4/81/2uE3PAV8bkG39X1Vl956jev3uL/Ch9KNaPAfGiahmIuSzdtCC2oyi9dz5CB8XzsFYp7ZnoEZMQUpA/KET16AMWSPCc4I0LwffpJ+rBq5AJvjoEcU1h5UnxbaGc9UtXXo109Myol60b6b4YDLVMTIleju0wqLMg97PgEZoPLh6iOJoltUB7EA==
    username: AgAtsR+20dZa+lz9I+dHyAfq7J/Uhv8Lfm0NKZL/2Lr1YfJqOwWgOrskSKvrMmvCNYPE+soTiWmIWsjRxvnNq6ABYokR6GCOseMZztXtzr4rxjkmeSRE1lcAassFUXkxMCoObYS/bJ1UPphn35rVQa6qrdiNXZl5CAkwp9BhthM3vLpTbCRQaAiQjjY5ApigSgIuPV4HShf9DRBQJS7HagImoMLa4VIyfwzvRXjstI4txt7rvJOo3K3hVrmipoWCIa9VlMx3OSXWXhinpjz61aNNQ2/kVzwk5IsDCXfOdukTdUuvizlLjFTqzbCZQCkxG8OwVcQWRT8gGjSXq4Ec5X7Q1ZkZ/du7Rtc2EG26ruYPTBNIsx5Ni6Tc6TgmPI135lt5WSmg/Rku5aJa/5y6w6iVLQYCgdThacJMosUaP7rI93g6dIeMLsT4w0IDtv3t67NLcGNcjqC2uEwNb2QOZ9yIiX8Hqw52aN7ZxWu8KkgsGKIaoAXOTrkhx+gPG9EJjxL6RArH/OJanWhBL+VfrtXZ0PyRoUh86ujhE9SfhD9sauhmsC8+TYE/bsHE6e7k42cm2WC2TBi7HqcmWdCWN/PQqL/03Nh4EvUMjYMprGEPz/WP6tYx3U6+/IYGm1Dnh2UygtChXum3yJrdzTfLSmz6IZx2u0r6frQtyfNiW6TKoq1gAIftxjXb8oWL5EhkiZ+p2yXW1CZh0g==
  template:
    metadata:
      name: postgres-superuser
      namespace: shared-data
