---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-admin-secret
  namespace: shared-data
spec:
  encryptedData:
    password: AgB8ygsUkB75CBiLhACoMG3eJO+Kjg8IJWlJN6JbuCUQtCHAAHBmEhpLbHzdddPr4WCMvl9YE7D7tBhn0jVJMt5Sq+3bkMIxLvhz5pyfPCUabXeZ/0BOyq5uaL4m+RcIl7df2abRAMn7zAB+3eHDwSnoJ4sXX8XiO4qnwNKSJZCxNMKjN17FAtl259SLtT86v7p9/6lOY0bYshJK2G8r5cAq28hXcaOxkGeeF0pzpHRzVP8zxolOLAlFdiL/pHs8tgIuNaP6BAGXVHynD502CPVLanV6ugRjUi/gjVrlaj28XpC+kRJTT2Rsh/Ik2S0gvgny8K3JZm/20LPqYDFGRXRRaQ6b+GFEOYGbp/fE8n/PxXUsp4DcK/bCxDj99JOmjNnPDu0fLIe6Lf5xocppziWwRvBCxCFSyhAqv9kx3k39dhOtEVj1V9Gup0hVj/r3X4CUqqN5VyBthHAmIOYLxYpar1ZmZ8/mNEcjmgvp0sV5JjSH1qphey78b3zjjA1iRIa09P1jJFcC2ZQD+v/hJUL3cKALEOyvwK2kYgGnZ/CDXsQGvbis2uZ/0xciulxknw44YCEy5cV/x5xCqR0dx1W1aNdUU6XClfvYGcUsHqco0VdetwlA8kLBj9TuKm6fyELbdkLQRr0L8eMFxnAqNJKXdnT1YIqaO0ZvDEfAD7hbR7l4X1wR1hFcrD/CXDR333QI/56kLewvR5DnCw==
    postgresPassword: AgA50kHWhbFltbHT4JLEKx+w3ouYUWKKNJWvT835B4ygt0I31xHEF/WMHFK3D4dYrq9arkbTbQZpxklljUPDNLwcfooFk+UfVJrW4A3T55byc0P2B9wDnTmHKqopQZoTouyaymFsrngBjKyJpufgwZHYgEvtJY1LILz/hjc9H2vtEXGgTuutyazXJh7Uk4lTj0LBRsW+FJM5tEjmVY+0+VHUnO9VgbNlXzukmv7o2U6UxdwDPlSVEZYKizILvQVyvYLgIunWgSJiSdp+8QhiRNgWNVfSdsjWjfxZ12UhCeEATb7MN78hKdgHNFliNsic8ajwoK+tfUlW49UEM8blfIlqxXYAWw9E07aM7cm2SQYIrfW7dfYH3bp0Q23zYZAU5D0alM7UT4yXBnRv796Q5B9gQYULjrgej67d1AISo1JoEktaEX1qxToHg6FlW9Bv14/wKGWZ86Efe8DF1ke6ZRG5O8uU9rozZFt2wkiNpWleG3sn0cnJ+qrEtlkd0oUB9GQ60SJKfXJVr1QeQ7hqJeVf1qj0JMnsA9jm8e1YFMIGdp7fXD7QuaIsntS9dPaT5qRPnhW90m1f3QPwQzFxnIbdrh91K0oQRmF63lccNouxbEoVTF17DMSmxHMdGPpLxBT7ZHXvuuB6kRxuu92xoWxBNwf0ldb3R7tWxMyB5+5PQSQiMJcAyCsPQOqaPgWHGM/z06XPyDG6nXfZyQ==
  template:
    metadata:
      name: postgres-admin-secret
      namespace: shared-data
