---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: personal-finance
spec:
  encryptedData:
    password: AgBT+L4YPp1LXvDEbi3SQH7LNPSfVgdJMLlQ7ZqAya8W28u4nLisG75ExQ+vV7cPCsW9b88aNsCt+Qa1aJltu5P+llamMxWc3Ekju67p0D00Zav9WgAS3a9WncsKutIDY9OyWtLikcP9ZKwwFtb4d5j6CENdaiNwz0W2awlmESxAhdM1ApJSB8cvW1+6T/vgwvpDj66AAwDFCzWbSPRjH3Ymt/3yREBsGu01Y0h1+vPAQ/dLrudO6XEbHTNpRpbnCEhk70mfXp3lzVYmoZCFDugY+Zfg2cON6sqYYNbJfBo3HIYySlnurVIb91xdcsjVehHHi5cmxdlR6zSlcA5nHruBHeuwxuNu1+ivU4gqc7o04NN6pyVd0jreM9YVs05a9mDC6VoQFvgeMjE+Dgb+WVFNvbDEzYIfHvkh4zVi9TM41ZwJrfAIYFLSERlBeRMnPmpv5eii7ebkXLQ50ZyDkVbCo/LILtgNrlC3KqCfA3SEfBH9fm0JLaDrdJpyu8kuY958N1VA+G8pBK70AprCX//ShDZCZGFL62VLJeydlldBk/NDIbaTGYBrxrocHVa2uqwj+B0zhUzsAI8QO7jZoeAwNvMUO6ORVpd5glqQ8wRyewEG2UkrkWpEA2IRX/yVoukjrxScVPDskl6UuqSqiv+9dmQeMq2/zOa8lXNL33SpBLbdNzQnNvBHFfGtuk5UuKZ7ccdAE4so2qmxtQ==
    username: AgBQaVp39CpKv4hr1sM6F6JSll79nKVhuT9AJofOePaF/825EzvIw/VHUmYNi6R0tlZnrTmykLkA+XXN6WNJKegGTcWLdQqAiE2EBpDjuxx4k8yaf1DPuixNK2GcAHekEovD2UVFsBjVy52Ctmp2B47h4BHy1078urOOLQI++Uesi1tRSTF0k07Fd2ZkqHp0EtmRMj7WVBBMWuO8pQfcnkgK/i1T8U1Nohld0Ce3Dk6Mm1SyxGI+3hgAoWKIbySA9032fxifFdYJFRQToJhUkJoYRONMXVZkIb38b4+/qwYc17d5nIvwlOal73brp5a2spU4ZXIlk476WeXc86hqhHkPlcH8oTat2dLB5mmN057xQw9/IGcQT8A4OoYnFkHHuYAyNxocQ34nuFrvnmqbcQ3oMBubqTgwtc5mNTM2Fa6NjAaisNDW382vHaa/teU5dSlOhaaejIwgiacw7KZ2iwyt79FnbU5LOpMhrPnpNKLJXZHMlQBpIahxCZ2KnQAsvQs6QKbfXcGMCnQKSRCITBsWzkSP9VdoDmMoyfoHQ9seTjSCol4UAa1p/cmgv9WuDbcNORtg0IV3EzV3dVGn771r3qk+IOX+naKATdvEUpaYR9I2aoe+SOWmWAbcYFlhJI7sZtzEB1wEp+kRFOaJRTWN77v2z335vwybCosjI2zN0RwRNUlQGOzTkv7w/dqlUSIVqHE6xw==
  template:
    metadata:
      name: db-credentials
      namespace: personal-finance
