apiVersion: longhorn.io/v1beta2
kind: BackupTarget
metadata:
  name: default
  namespace: longhorn-system
spec:
  backupTargetURL: "nfs://192.168.0.13:/srv/backup2/longhorn-direct"
  credentialSecret: ""