deploymentMode: SingleBinary
loki:
  auth_enabled: false
  commonConfig: { replication_factor: 1 }
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index: { prefix: loki_index_, period: 24h }
  storage:
    type: s3
    bucketNames: { chunks: loki-chunks, ruler: loki-ruler }
    s3:
      endpoint: http://garage.garage.svc.cluster.local:3900
      region: garage
      s3ForcePathStyle: true
      insecure: true
  limits_config:
    retention_period: 720h              # 30 days
    ingestion_rate_mb: 10
    ingestion_burst_size_mb: 20
  compactor:
    retention_enabled: true
    delete_request_store: s3

singleBinary:
  replicas: 1
  persistence:
    enabled: true
    storageClass: longhorn
    size: 20Gi
  extraArgs:
    - -config.expand-env=true
  extraEnvFrom:
    - secretRef:
        name: loki-s3-credentials
  resources:
    requests: { cpu: 200m, memory: 1Gi }
    limits:   { memory: 2Gi }


sidecar:
  rules:
    enabled: false

read: { replicas: 0 }
write: { replicas: 0 }
backend: { replicas: 0 }
gateway: { enabled: false }
chunksCache: { enabled: false }
resultsCache: { enabled: false }
lokiCanary: { enabled: false }
test: { enabled: false }