---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: garage-secrets
  namespace: garage
spec:
  encryptedData:
    adminToken: AgAl7zxeDc8jjcB6SONqWws704mC8CzIx7hDMWFx8qOncR0v6eBNEBokteeCEHJg0It+jOa2cEcxJmlDfW7Vnakpcr8DZWApGwMGe75q6fOciSvO2LaVLL9q3e2ZXpEH+mANOB8iX+h+G5eQU8nkRhCuvuuJk3xWydvjyYZBbCXTBHO8qL8aQN0sRaB0rcplaUxU9T84v8rQDduKGhUxLQIj6eNUL5l2/MP5D1a8jQHnPvupvXYzHqEuEg9LV3rwktPQtF+YIUs5xxPlDXNSgYnVkkKFcutI5Tu0y88sYI9tnwzLvQoNDKFgb9IC7t7GClCUkcLToEO5A8ICk6IpoGaSdtXODLPfxIH6p+hU+6rkAwDCsHCrFISejR3BmEli20KDOJuQfptB/PnD2yDIgMLz4p2iav8xAGRaI8I1adnns5SxiGSYfKgAeOLaKvmFW0sd+yfCkkFXwtmVlI8HRoqaQdFEU7FZAUmM0l2V5CuvmiYhYI9kJO34QVVQLw7SmTMFdFn08TC7LKPhCpiF8N64znRv58Oi4M+1fH0Z51epB7n6+VYiY+uo3kcJclTmzSoXo6gUjGWIPTOR9oq3KbNbB963cpeRqJwo6oDm6eOoXHPoA8E58X7AqR0vBIe+wL7WmiQlIaRhuBahQrZsMDFc7UQc07fBN/AF016Vrat+PWf2/G/0Yr+z4Hj5dG0rpxjiroKPKW1WTQlhq9Ip0uzmyqmuW0btUjlWwtWfv47uLpToUZhoTL38/Ot6Ug==
    metricsToken: AgBWYGNT5dkJNpZrdp6QANyzDweDyXl5TzC4iMr91+/MjarklmSh8sB6X0hbXs8uSiMO4N7o7k0O2kD+5ehckBjQgyE2SN92ZCUSl9Ip3Q1aWf4KuVRiEMBgM1Rkx+Cm787xfGhCxe89tg+XeGoavD4O2CVmQ1ka6S8sh9zb9ingX2OtIHqpA4/G4GDeyoF+O4EWZh71H6L2Qf12KZro5e+1N731XeeC5gVwgx35/M8lXyrBNn0zggh68IpagPuSAU+8EXIAk7zR4fvZzBl+4ZoRqMIhq9BwwVJFAqc+N0DSqccUPZ+FmjIZCcrwLehJDpmlbspm7aQLxzZjtE8iRrzv8Y/PSz5XUhfp7u+QhrcdT8Mu/1eKYDzIHjHBDBDPAA4GZucr7C7kf+fVLc3Y568kwihgbrMGRf27U5LW7+E+sdb0IGp4MAPaVwzhUPpdOUY18s/P1NEuRlLvympjGhHPSHLliCnSNUYgjRre1leyUgC4vswxMlVXr2PnCDgLRR0iFjY05J8lNl2BEIPGVTctP4bhUM2BBQzGzIV0LisbgwQG4aMoG0uW3+qYtG9GyOOvipcse4d0UtUqdww2QiXHalVWpzTnvRMrxxar2NBevBeNKVcCDU8oGYaIKcc9WgwkKdO/mD6iBPmngr0GfxSvNmfhcjQzCz3JPJP19GL0h1ShLaI1TEj1cnXJ4t/99F6dFMv+rKzVKLaueWJmwnl6kIP3iTsvrPYfyQEs1zbtsqo7yTPP+dbxcjYfwQ==
  template:
    metadata:
      name: garage-secrets
      namespace: garage
