---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: garage-webui-secret
  namespace: garage
spec:
  encryptedData:
    AUTH_USER_PASS: AgBHk0MDwSYF0Pa6nY5oX8M9w9BGo8yKubG+erPEHv/Pth1kGDfOVwbxHBppU6WFmFanAzLHZ7SV2UwVvcvKKYY+KLsez9py2ahuTU9lWin1buJsvw4yKWss/fYZP2Y+JUkcCbaPd3/y59VeS594h5RykbkPMh9yzSS9wbGRq+toOzMjKOXOux6mfLATy0XUp8P6mo47n+gmjW3YafuvwnqH60l9GaFO4T0XY970suOxOSG8MAxGZIKxuolmAtv1zowAxri4fNcJ/HEuNWOgBajyNf0mNBg/A5TqTqEt+afztRxM1xrWMcHJlCVkzaEYqupcvxCQYXcTv4A9N4gPIu9DwHP8bB0pZOmfwJCC+0sqFF7dq+axiJM1aktll+ZNZHm8vqzqmHVIMaNunVX4Byy5VHXZUE/7DKM9jtbbFDKUeFtFwwkfX5vgLp6E++zyDfJwvOqwhCv/wXn6nJ9DQD5MlHrIxhGUsC6FK2VFoVG5P3uoKSRjOedOT21voZPBhLDhOgniuu3RP5fOHZa4Aflq5iZtAvLZySbELIkmLUMeplg8RUjnkgYl6H76r5YupvN/wE6/7W7sjqjrLTE/znRo7e3+Dv+ftolSS0wqwdAPP3eRqUoZ4lgm6vS5BCedbtxPjp0h5QgRLolVN2JY5fp7twlrPlACXqOS9dqFc4OIEDD4ZAq5SsB1LJ6+mfNeX4rRpTvluLgdTQbqNEZJjBGiVMwyaYkA6ud56pJzLtoAmmeQqv5MghS1we7kpmFVu+M2ABhqcjbhlfrmjwMX490DoqM=
  template:
    metadata:
      name: garage-webui-secret
      namespace: garage
