apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clickhouse
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/gunnervj/homelab.git
    targetRevision: main
    path: clusters/home/apps/clickhouse
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: shared-data
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true, ServerSideApply=true]
