apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 88.6.1
      helm:
        valueFiles:
          - $values/clusters/home/observability/kube-prometheus-stack/values.yaml
    - repoURL: https://github.com/gunnervj/homelab.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/gunnervj/homelab.git
      targetRevision: main
      path: clusters/home/observability/kube-prometheus-stack
      directory:
        include: '{httproute.yaml,grafana-admin-secret-sealed.yaml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true, ServerSideApply=true]