apiVersion: v1
kind: ConfigMap
metadata:
  name: affine-config
  namespace: affine
data:
  config.json: |
    {
      "server": {
        "name": "AFFiNE",
        "externalUrl": "https://affine.naadroid.dev"
      },
      "auth": {
        "requireEmailVerification": false
      }
    }
