---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: affine-db
  namespace: affine
spec:
  encryptedData:
    DATABASE_URL: AgCgufwIowDGJNvq0LNxi4W4ELm3zgnllY9BQnemUgxlkino+Dm0Au6lU8MQC17SjbJcP4IIzC61hCabhLNKT0i8ug1N4MMWx32vgmJXNElMEU2XJmDA0uSDWLVa3aYnKQ+xMiz6OGqWy427mQNypYcbtH+pPBGsGl7etAmShPblUAgGJBaWHyRtaqRufUybOcy3/w4ikqB92EYHRJg6+oB8MyQ4a2gYG9aKpVzpeCpMjNgMtMwJazbefxkhczT+GFu8SHiAiEohndEqW9lCFoxGr6jRjFe0Db1gkkStMqkAFKofWR0+Q5/CuMYb1SVzv6Z4CuUq81/ntFCQaJkOAI33glGDWMC4k9HSu+N/ROhki8jwrgzULiVmnhw3o4Wwlf25p9DdGWTns5A+cmCK+l+QSvi1ZQs4TWbTrOT6ECtBsK2kEN6kCQh/YW4V1UHW1ygNmzsgwvyNFB4lVSv/PZt9SV161jhjtMDGe/7ibHy+oZ8DMhuz4X18CJ9NoOoYaVTBwzA1KCnLOfwWla2QDEgMFKlOjuE2piNgpDjNmG5/X93OajEcbIPEcj3Ize1WVephoKfbkOU3spJ+k05uf+JI4pR0xDnXWQpNzB6wEnc3ikurZ1/4Fyv/eJCGRoQ40qEvQ1icOh7NwX9vEEseE7v2zf8sqp6RLMCp4SLfqB4AXtU9TIQzbzLfmX49l/zlhuLEI27ydHOstc1EpFOu6KfSGo0VuBmDrKFNvkvbNx24Ktwp+19hSHfyapDRRAoayoz15D+ox56M4dRuaC2FQkHicY9/K+0bjgIwoTWuFO8rH1pdaB8=
  template:
    metadata:
      name: affine-db
      namespace: affine
