---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgB6rwHBag4z0MlYHVUD4a144oZy0Kc472e231wjygNX7zigRSKtLmXzzZX8V5uqPxzJI9V+CZIrG3C6Tj5C+gLHnrZOD5ir7/d+1Hhs62qztrpOYuLfDkWdRP3XHIey8f7kw+hEfmwZ8uc/o0iHw0Z9Ln66K/ke5wLMVVzKcNat6pmhOkdIDDX00gTOZ58XnwvXr+iprNED3fDl5yyO4tcjXtCuN0YXxtqiC0lGxqcUaxV3MgQU8agqK2lRt75yThkxjLPsedC1wMwL+0EOC9Y9MLUCjoMboPCDTGwPBBQaOf71JUpNVYuH9DY85isstQuLPcqwRUrER9GMBraX6+jm8AyrCcIUfRsFbD0mxa6Ny2wtS7hpLPKgeKDGHPSWugBu1dxeiovTBQ+jyed9KeWYbTrYCYoArjTIL2cogAKfA0W/gCkh4bwB3Jdjdh9vPj6P9ZZ4IMZjvAoYZfzcJgP77n5qa6vaHXXRoR+Qug5nO423atTxwMjkoE9eidqbvhP027vjZFQrN2OiUAj3+iJqfrAhzplaKrPoY5JZuQyz1iQZxUy6OwDSoCmUTOXcTcaGwOAPueCFvNmgUnePBaPeA6T3CpxxsBGYrEFKiA9qHzYgXcLPfYfiqPp/8ok711Jl2o0zl4W7Pxv4MLQkwft+SF91UvrAjoksE+9ICbCCtSO+NpY5izs5Uf+Xjs6SxRL4QzwZ7xJPVAml/iGOV1vrZTTE8sVa0jO+85276qptN/aVN+nLJax+fArlnebA3H0exoDmzdcEYdCu/6Nif0C9ATkPvGLTY74XeptVWduJ++dqH68q4UtW/x5y41oVlqLUFi3GzXNPoPEDrpbt/3t5hChoWmLgdCrlBIpBup9lopNS+GUcBU6o/olB8TLk
  template:
    metadata:
      name: velero-credentials
      namespace: velero
