admissionController:
  replicas: 1
  resources:
    requests: { cpu: 100m, memory: 128Mi }
    limits:   { memory: 384Mi }
backgroundController:
  resources:
    requests: { cpu: 50m, memory: 64Mi }
    limits:   { memory: 256Mi }
cleanupController:
  enabled: true
reportsController:
  enabled: true