---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: frontend-secrets
  namespace: personal-finance
spec:
  encryptedData:
    nextauth-secret: AgBZZk6VrZ32RqcXX7iFRRElwBYhueW8i2mP+RM9ubQ09HDJtIobNYI49h/kRh++sOIAYLshpvWe7vzsPLm0/jH8B2oUx7yLUnk7XN80bQorh2aBfcF4KgJCyX7s+b81F3GOdDNGxs1gAXW5GC4oZY1Y3bFPJNPJMX282vUysld7x/jxM7d7RFwh11uf8ay1O+WBulIQgLDULOQcwRpbZuJWrAh9bCBYMhM53J3rYNOaaOUEO9Aw60TcVcfnBOi1/1KSATuBom40ROfhwJZ/afHCRtoJXrXaIhQo+93+k7GCYo40Vftbszach3mRg5QZPY6V4Dvup74w3dQuPghR111L+N2gNvjULupASkCJHPGtMsoJ8mjM4/LFAg1LvCgGz+HpD0PTMHgNohgkyiCkVL6EUBriFI2kNKQCjj9MKwjIlodetO81OoFmlB7xUyIyhpjsz18p9jU00lULwPWkZQqkZoiKjJXKciXVXZBPUKxdMnxFiQXalYKUibDaVeXfH/UyWcR0BQrxhsPyyj+pNCUK150greOev0J5+ux+pp7zfV7Bu5JFHkitAIkbP0SjzfcRotscC0Jq2IZelwnpICkUtVH0v1gjcRJqFhhlct0ibTVmm+s+Y+qlJHRd3XjJT0ghCaChP2AE9ROpO6ngVZ+GDJGn/z3+Pyf/nuT7Nq7ocFFHqY4yMiRSKqOpCi3RUBbFrdj9CeNCm0+C+ZeYonloFL3Fh9V4tf12KlSchf7tLkqUTM6j22mv+nNi8w==
  template:
    metadata:
      name: frontend-secrets
      namespace: personal-finance
